//package gigatools // if this is uncommented the whole thing explodes apparently

import com.intellij.codeInsight.completion.*
import com.intellij.codeInsight.lookup.LookupElementBuilder
import com.intellij.codeInspection.ProblemHighlightType
import com.intellij.lang.LanguageAnnotators
import com.intellij.lang.LanguageExtension
import com.intellij.lang.annotation.AnnotationHolder
import com.intellij.lang.annotation.Annotator
import com.intellij.lang.annotation.HighlightSeverity
import com.intellij.openapi.actionSystem.*
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.editor.DefaultLanguageHighlighterColors
import com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.TextRange
import com.intellij.patterns.PlatformPatterns
import com.intellij.psi.LanguageInjector
import com.intellij.psi.PsiComment
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiWhiteSpace
import com.intellij.util.ProcessingContext
import icu.windea.pls.lang.codeInsight.completion.contextElement
import icu.windea.pls.lang.codeInsight.completion.scopeContext
import icu.windea.pls.lang.definitionInfo
import icu.windea.pls.lang.search.*
import icu.windea.pls.lang.search.selector.*
import icu.windea.pls.lang.util.ParadoxLocaleManager
import icu.windea.pls.lang.util.renderer.ParadoxLocalisationTextRenderer
import icu.windea.pls.script.ParadoxScriptLanguage
import icu.windea.pls.script.psi.ParadoxScriptDefinitionElement
import icu.windea.pls.script.psi.ParadoxScriptElementFactory
import icu.windea.pls.script.psi.ParadoxScriptRootBlock
import icu.windea.pls.script.psi.findProperty

import liveplugin.ActionGroupIds
import liveplugin.PluginUtil.*
import liveplugin.getStaticField
import liveplugin.whenDisposed

// depends-on-plugin icu.windea.pls

// #####################################################################################################################
// #### EXTENSIONS AND UTIL
// #####################################################################################################################

val textGeneratedBlock = "WARNING: The contents of this block are generated by script, any manual changes will be overwritten"
object GigaToolsAttributesKeys {
    val PROPERTY_LINE_KEY = createTextAttributesKey("GIGA_TOOLS.PROPERTY_LINE", DefaultLanguageHighlighterColors.STRING)
    val PROPERTY_KEY = createTextAttributesKey("GIGA_TOOLS.PROPERTY", DefaultLanguageHighlighterColors.FUNCTION_DECLARATION)
    val PROPERTY_NAME_KEY = createTextAttributesKey("GIGA_TOOLS.PROPERTY_NAME", DefaultLanguageHighlighterColors.CLASS_NAME)
}

fun getElementName(element: ParadoxScriptDefinitionElement) : String {
    val locale = ParadoxLocaleManager.getLocaleConfig("en") // english for standardisation
    val selector = selector(element.project, element).localisation().contextSensitive().preferLocale(locale)
    val loc = ParadoxLocalisationSearch.search(element.name, selector).find() ?: return element.name
    val rendered = ParadoxLocalisationTextRenderer.render(loc).replace("\u200B", "")
    return rendered.ifEmpty { loc.value ?: element.name }
}

// checks if a given economic category is the same as, or a descendant of, another
fun checkEcoCategoryWithLineage(categoryToCheck: ParadoxScriptDefinitionElement, categoryToMatch: ParadoxScriptDefinitionElement, map: MutableMap<ParadoxScriptDefinitionElement, Boolean>) : Boolean {
    if (map.containsKey(categoryToCheck)) {
        return map[categoryToCheck]!!
    }

    if (categoryToCheck == categoryToMatch) {
        map[categoryToCheck] = true
        return true
    }

    val parent = categoryToCheck.findProperty("parent")
    if (parent == null || parent.value == null) {
        map[categoryToCheck] = false
        return false
    }

    val selector = selector(categoryToCheck.project, categoryToCheck.context).definition().distinctByName()
    val parentCategory = ParadoxDefinitionSearch.search(parent.value!!,"economic_category", selector).find()

    if (parentCategory != null) { return checkEcoCategoryWithLineage(parentCategory, categoryToMatch, map) }

    return false
}

// don't un-inline these or the whole thing explodes for ??? reasons
inline fun nextNonWhiteSpaceSibling(element: PsiElement) : PsiElement? {
    var nextElement : PsiElement? = element.nextSibling

    while (nextElement != null) {
        if (nextElement !is PsiWhiteSpace) {
            return nextElement
        } else {
            nextElement = nextElement.nextSibling
        }
    }
    return null
}
inline fun prevNonWhiteSpaceSibling(element: PsiElement) : PsiElement? {
    var prevElement : PsiElement? = element.prevSibling

    while (prevElement != null) {
        if (prevElement !is PsiWhiteSpace) {
            return prevElement
        } else {
            prevElement = prevElement.prevSibling
        }
    }
    return null
}

// #####################################################################################################################
// #### TAG DATA
// #####################################################################################################################

class DefinitionTags {
    companion object {
        val tags = mapOf(
            "megastructure" to mapOf(
                "ruined" to "Some description"
            ),
            "scripted_trigger" to mapOf(
                "test" to "A test tag"
            )
        )
    }
}

// #####################################################################################################################
// #### PLUGIN FUNCTION
// #####################################################################################################################

// rewrite the body of a specified scripted trigger with a list of megas which have the matching economic category or a child thereof
fun buildMegaCategoryList(project: Project, triggerName: String, categoryName: String) {
    // find the trigger that we're going to rewrite
    val trigger = ParadoxDefinitionSearch.search(triggerName,"scripted_trigger", selector(project, project.projectFile).definition().distinctByName()).find()
    if (trigger == null) {
        show("Failed to find scripted trigger: $triggerName")
        return
    }

    // find the economic category we're checking against
    val wantedCategory = ParadoxDefinitionSearch.search(categoryName,"economic_category", selector(project, project.projectFile).definition().distinctByName()).find()
    if (wantedCategory == null) {
        show("Failed to find economic category: $categoryName")
        return
    }

    // start the block's text with a warning and description
    val builder = StringBuilder().append("{").appendLine("\t# $textGeneratedBlock")
    builder.appendLine("\t# Lists megas with an economic category equal to $categoryName, or one of its descendant categories").appendLine()
    builder.appendLine("\tor = {")

    // get a list of matching megas
    val megas: Set<ParadoxScriptDefinitionElement> = ParadoxDefinitionSearch.search("megastructure", selector(project, project.projectFile).definition().distinctByName()).findAll()
    val ecoCategoryMap = HashMap<ParadoxScriptDefinitionElement, Boolean>()
    for (mega in megas) {
        val resources = mega.findProperty("resources", inline = true)
        if (resources == null) {
            builder.appendLine("# ${mega.name}: no resource block")
            continue
        }

        val megaCategoryName = resources.findProperty("category", inline = true)?.value
        if (megaCategoryName == null) {
            builder.appendLine("# ${mega.name}: no category given")
            continue
        }
        val category = ParadoxDefinitionSearch.search(megaCategoryName, "economic_category", selector(project, project.projectFile).definition().distinctByName()).find()
        if (category == null) {
            builder.appendLine("# ${mega.name}: category has no value")
            continue
        }

        val matches = checkEcoCategoryWithLineage(category, wantedCategory, ecoCategoryMap)

        if (!matches) {
            builder.appendLine("# ${mega.name}: wrong category -> ${category.name}")
            continue
        }

        val locName = getElementName(mega)

        builder.append("\t\t\$TRIGGER\$ = ${mega.name}")
        if (locName != mega.name) {
            builder.append(" # $locName")
        }
        builder.appendLine()
    }

    // create a new block with info and content
    builder.appendLine("\t}").appendLine("}")
    val newBlock = ParadoxScriptElementFactory.createBlock(project, builder.toString())

    // finally, swap the trigger's block for the new one
    trigger.block?.replace(newBlock)
}

// #####################################################################################################################
// #### PLUGIN SETUP
// #####################################################################################################################

val pluginActionGroupId = "gigas.group"
val pluginActionGroup = DefaultActionGroup("Gigas", true)
pluginActionGroup.addTextOverride("MainMenu", "Gigastructures")
registerAction(pluginActionGroupId, "", ActionGroupIds.Menu.Tools, pluginActionGroup)

// regenerate lists for what counts as a kilo or giga
val gigaRegenMegaCategoryListsName = "Rebuild Kilo/Giga Category Triggers"
class GigaRegenMegaCategoryLists : AnAction() {
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return

        WriteCommandAction.writeCommandAction(project).withName(gigaRegenMegaCategoryListsName).run<Throwable> {
            // test triggers for now
            buildMegaCategoryList(project, "plugin_test_kilos_trigger", "giga_kilostructures")
            buildMegaCategoryList(project, "plugin_test_gigas_trigger", "giga_gigastructures")
        }

        show("Trigger Rebuild Complete")
    }
}
val gigaRegenMegaCategoryLists = GigaRegenMegaCategoryLists()
gigaRegenMegaCategoryLists.addTextOverride("MainMenu", gigaRegenMegaCategoryListsName)
registerAction("gigas.regenlists", "",pluginActionGroupId, gigaRegenMegaCategoryLists)

class DefinitionPropertyAnnotator : Annotator {
    private val prefix = "## "
    private val pattern by lazy { Regex("(?<=\\s)\\@([^\\s]+)") }

    override fun annotate(element: PsiElement, holder: AnnotationHolder) {
        // only comments
        if (element !is PsiComment) { return }
        // only top level elements
        if (element.parent !is ParadoxScriptRootBlock) { return }

        val text = element.text
        // only specially annotated lines
        if (!text.startsWith(prefix)) { return }

        // get next non-whitespace element or bail
        val nextElement: PsiElement = nextNonWhiteSpaceSibling(element) ?: return
        // only definition lines
        if (nextElement !is ParadoxScriptDefinitionElement) { return }
        // work out what type of thing we're looking at for getting valid tags
        val elementType = nextElement.definitionInfo?.typeConfig?.name ?: "unknown"
        // get the valid tags or abort if there aren't any
        val validTags = DefinitionTags.tags[elementType] ?: return

        // mark the prefix
        val prefixRange = TextRange.from(element.textRange.startOffset, prefix.length)
        holder.newSilentAnnotation(HighlightSeverity.INFORMATION).range(prefixRange).textAttributes(GigaToolsAttributesKeys.PROPERTY_LINE_KEY).create()

        // find all properties via pattern
        val propertyMatches = pattern.findAll(text, prefix.length)
        for(match in propertyMatches) {
            // the @ at the start
            val markerRange = TextRange.from(element.textRange.startOffset + match.range.first, 1)
            holder.newSilentAnnotation(HighlightSeverity.INFORMATION).range(markerRange).textAttributes(GigaToolsAttributesKeys.PROPERTY_KEY).create()

            // won't be empty or null otherwise it wouldn't match the pattern
            val property = match.groups[1]!!
            val propertyRange = TextRange.from(element.textRange.startOffset + property.range.first, property.range.last - property.range.first + 1)
            val propertyName = property.value

            if (validTags.containsKey(propertyName)) {
                holder.newAnnotation(HighlightSeverity.INFORMATION, validTags[propertyName] ?: "No description").range(propertyRange).textAttributes(GigaToolsAttributesKeys.PROPERTY_NAME_KEY).create()
            } else {
                holder.newAnnotation(HighlightSeverity.ERROR, "Unknown tag \"$propertyName\" for type $elementType").range(propertyRange).highlightType(ProblemHighlightType.LIKE_UNKNOWN_SYMBOL).create()
            }
        }

        //println("ANNOTATED: $text")
    }
}
val definitionPropertyAnnotator = DefinitionPropertyAnnotator()
LanguageAnnotators.INSTANCE.addExplicitExtension(ParadoxScriptLanguage, definitionPropertyAnnotator)

class DefinitionPropertyCompletionContributor : CompletionContributor() {
    init {
        extend(CompletionType.BASIC, PlatformPatterns.psiElement(PsiComment::class.java),
            object: CompletionProvider<CompletionParameters>() {
                override fun addCompletions(parameters: CompletionParameters, context: ProcessingContext, resultSet: CompletionResultSet) {
                    // get the comment element
                    val comment = parameters.position

                    // find the next element and check that it's a definition
                    val nextElement = nextNonWhiteSpaceSibling(comment)
                    if (nextElement !is ParadoxScriptDefinitionElement) { return }
                    // get the valid tags for the definition's type
                    val elementType = nextElement.definitionInfo?.typeConfig?.name ?: "unknown"
                    val validTags = DefinitionTags.tags[elementType] ?: return

                    // add all valid tags to the list, along with their descriptions
                    resultSet.addAllElements(validTags.keys.map { s -> LookupElementBuilder.create(s).withTypeText( validTags[s] ) })
                }
            })
    }
}
// register the completion thingy
val contributor = DefinitionPropertyCompletionContributor()
val languageExtension = CompletionContributor::class.java.getStaticField<LanguageExtension<CompletionContributor>>("INSTANCE")
languageExtension.addExplicitExtension(ParadoxScriptLanguage, contributor, pluginDisposable)

// make sure stuff is unloaded
pluginDisposable.whenDisposed {
    LanguageAnnotators.INSTANCE.removeExplicitExtension(ParadoxScriptLanguage, definitionPropertyAnnotator)
}

println("registered")