//package gigatools // if this is uncommented the whole thing explodes apparently

import com.intellij.openapi.actionSystem.*
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.project.Project
import icu.windea.pls.lang.search.*
import icu.windea.pls.lang.search.selector.*
import icu.windea.pls.lang.util.ParadoxLocaleManager
import icu.windea.pls.lang.util.renderer.ParadoxLocalisationTextRenderer
import icu.windea.pls.script.psi.ParadoxScriptDefinitionElement
import icu.windea.pls.script.psi.ParadoxScriptElementFactory
import icu.windea.pls.script.psi.findProperty

import liveplugin.ActionGroupIds
import liveplugin.PluginUtil.*

// depends-on-plugin icu.windea.pls

val textGeneratedBlock = "WARNING: The contents of this block are generated by script, any manual changes will be overwritten"


fun getElementName(element: ParadoxScriptDefinitionElement) : String {
    val locale = ParadoxLocaleManager.getLocaleConfig("en") // english for standardisation
    val selector = selector(element.project, element).localisation().contextSensitive().preferLocale(locale)
    val loc = ParadoxLocalisationSearch.search(element.name, selector).find() ?: return element.name
    val rendered = ParadoxLocalisationTextRenderer.render(loc).replace("\u200B", "")
    return rendered.ifEmpty { loc.value ?: element.name }
}

// checks if a given economic category is the same as, or a descendant of, another
fun checkEcoCategoryWithLineage(categoryToCheck: ParadoxScriptDefinitionElement, categoryToMatch: ParadoxScriptDefinitionElement, map: MutableMap<ParadoxScriptDefinitionElement, Boolean>) : Boolean {
    if (map.containsKey(categoryToCheck)) {
        return map[categoryToCheck]!!
    }

    if (categoryToCheck == categoryToMatch) {
        map[categoryToCheck] = true
        return true
    }

    val parent = categoryToCheck.findProperty("parent")
    if (parent == null || parent.value == null) {
        map[categoryToCheck] = false
        return false
    }

    val selector = selector(categoryToCheck.project, categoryToCheck.context).definition().distinctByName()
    val parentCategory = ParadoxDefinitionSearch.search(parent.value!!,"economic_category", selector).find()

    if (parentCategory != null) { return checkEcoCategoryWithLineage(parentCategory, categoryToMatch, map) }

    return false
}

// rewrite the body of a specified scripted trigger with a list of megas which have the matching economic category or a child thereof
fun buildMegaCategoryList(project: Project, triggerName: String, categoryName: String) {
    // find the trigger that we're going to rewrite
    val trigger = ParadoxDefinitionSearch.search(triggerName,"scripted_trigger", selector(project, project.projectFile).definition().distinctByName()).find()
    if (trigger == null) {
        show("Failed to find scripted trigger: $triggerName")
        return
    }

    // find the economic category we're checking against
    val wantedCategory = ParadoxDefinitionSearch.search(categoryName,"economic_category", selector(project, project.projectFile).definition().distinctByName()).find()
    if (wantedCategory == null) {
        show("Failed to find economic category: $categoryName")
        return
    }

    // start the block's text with a warning and description
    val builder = StringBuilder().append("{").appendLine("\t# $textGeneratedBlock")
    builder.appendLine("\t# Lists megas with an economic category equal to $categoryName, or one of its descendant categories").appendLine()
    builder.appendLine("\tor = {")

    // get a list of matching megas
    val megas: Set<ParadoxScriptDefinitionElement> = ParadoxDefinitionSearch.search("megastructure", selector(project, project.projectFile).definition().distinctByName()).findAll()
    val ecoCategoryMap = HashMap<ParadoxScriptDefinitionElement, Boolean>()
    for (mega in megas) {
        val resources = mega.findProperty("resources", inline = true)
        if (resources == null) {
            builder.appendLine("# ${mega.name}: no resource block")
            continue
        }

        val megaCategoryName = resources.findProperty("category", inline = true)?.value
        if (megaCategoryName == null) {
            builder.appendLine("# ${mega.name}: no category given")
            continue
        }
        val category = ParadoxDefinitionSearch.search(megaCategoryName, "economic_category", selector(project, project.projectFile).definition().distinctByName()).find()
        if (category == null) {
            builder.appendLine("# ${mega.name}: category has no value")
            continue
        }

        val matches = checkEcoCategoryWithLineage(category, wantedCategory, ecoCategoryMap)

        if (!matches) {
            builder.appendLine("# ${mega.name}: wrong category -> ${category.name}")
            continue
        }

        val locName = getElementName(mega)

        builder.append("\t\t\$TRIGGER\$ = ${mega.name}")
        if (locName != mega.name) {
            builder.append(" # $locName")
        }
        builder.appendLine()
    }

    // create a new block with info and content
    builder.appendLine("\t}").appendLine("}")
    val newBlock = ParadoxScriptElementFactory.createBlock(project, builder.toString())

    // finally, swap the trigger's block for the new one
    trigger.block?.replace(newBlock)
}

// #####################################################################################################################
// #### PLUGIN SETUP
// #####################################################################################################################

val pluginActionGroupId = "gigas.group"
val pluginActionGroup = DefaultActionGroup("Gigas", true)
pluginActionGroup.addTextOverride("MainMenu", "Gigastructures")
registerAction(pluginActionGroupId, "", ActionGroupIds.Menu.Tools, pluginActionGroup)

// regenerate lists for what counts as a kilo or giga
val gigaRegenMegaCategoryListsName = "Rebuild Kilo/Giga Category Triggers"
class GigaRegenMegaCategoryLists : AnAction() {
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return

        WriteCommandAction.writeCommandAction(project).withName(gigaRegenMegaCategoryListsName).run<Throwable> {
            // test triggers for now
            buildMegaCategoryList(project, "plugin_test_kilos_trigger", "giga_kilostructures")
            buildMegaCategoryList(project, "plugin_test_gigas_trigger", "giga_gigastructures")
        }

        show("Trigger Rebuild Complete")
    }
}
val gigaRegenMegaCategoryLists = GigaRegenMegaCategoryLists()
gigaRegenMegaCategoryLists.addTextOverride("MainMenu", gigaRegenMegaCategoryListsName)
registerAction("gigas.regenlists", "",pluginActionGroupId, gigaRegenMegaCategoryLists)

println("registered")