//package gigatools // if this is uncommented the whole thing explodes apparently

import com.intellij.codeInsight.completion.*
import com.intellij.codeInsight.lookup.LookupElementBuilder
import com.intellij.codeInspection.ProblemHighlightType
import com.intellij.lang.LanguageAnnotators
import com.intellij.lang.LanguageExtension
import com.intellij.lang.annotation.AnnotationHolder
import com.intellij.lang.annotation.Annotator
import com.intellij.lang.annotation.HighlightSeverity
import com.intellij.openapi.actionSystem.*
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.editor.DefaultLanguageHighlighterColors
import com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey
import com.intellij.openapi.util.TextRange
import com.intellij.patterns.PlatformPatterns
import com.intellij.psi.PsiComment
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiWhiteSpace
import com.intellij.util.ProcessingContext
import icu.windea.pls.lang.definitionInfo
import icu.windea.pls.lang.search.*
import icu.windea.pls.lang.search.selector.*
import icu.windea.pls.lang.util.ParadoxLocaleManager
import icu.windea.pls.lang.util.renderer.ParadoxLocalisationTextRenderer
import icu.windea.pls.script.ParadoxScriptLanguage
import icu.windea.pls.script.psi.*
import liveplugin.ActionGroupIds

import liveplugin.PluginUtil.*
import liveplugin.*

// depends-on-plugin icu.windea.pls

// #####################################################################################################################
// #### EXTENSIONS AND UTIL
// #####################################################################################################################

val textGeneratedBlock = "WARNING: The contents of this block are generated by script, any manual changes will be overwritten"
object GigaToolsAttributesKeys {
    val PROPERTY_LINE_KEY = createTextAttributesKey("GIGA_TOOLS.PROPERTY_LINE", DefaultLanguageHighlighterColors.STRING)
    val PROPERTY_KEY = createTextAttributesKey("GIGA_TOOLS.PROPERTY", DefaultLanguageHighlighterColors.FUNCTION_DECLARATION)
    val PROPERTY_NAME_KEY = createTextAttributesKey("GIGA_TOOLS.PROPERTY_NAME", DefaultLanguageHighlighterColors.CLASS_NAME)
}

fun getElementName(element: ParadoxScriptDefinitionElement) : String {
    val locale = ParadoxLocaleManager.getLocaleConfig("en") // english for standardisation
    val selector = selector(element.project, element).localisation().contextSensitive().preferLocale(locale)
    val loc = ParadoxLocalisationSearch.search(element.name, selector).find() ?: return element.name
    val rendered = ParadoxLocalisationTextRenderer.render(loc).replace("\u200B", "")
    return rendered.ifEmpty { loc.value ?: element.name }
}

abstract class GigaListConditions {
    companion object {

        // does this definition have EVERY listed tag
        fun hasDefinitionTags(element : ParadoxScriptDefinitionElement, vararg tagsToCheck : String) : Boolean {
            val tags = DefinitionTag.getTagNames(element)
            return tags?.containsAll(tagsToCheck.toList()) ?: false
        }

        // does this definition have ANY listed tag
        fun hasAnyDefinitionTags(element : ParadoxScriptDefinitionElement, vararg tagsToCheck : String) : Boolean {
            val tags = DefinitionTag.getTagNames(element) ?: return false
            for(tag in tags) {
                if (tagsToCheck.contains(tag)) {
                    return true
                }
            }
            return false
        }

        // cache variables for hasEcoCategory
        var cachedEcoCategory : ParadoxScriptDefinitionElement? = null
        var ecoCategoryCheckCache : MutableMap<ParadoxScriptDefinitionElement, Boolean>? = null
        // check if a definition has an eco category or one of its children
        fun hasEcoCategory(element : ParadoxScriptDefinitionElement, categoryToCheck : ParadoxScriptDefinitionElement) : Boolean {
            val resources = element.findProperty("resources", inline = true)
            if (resources == null) {
                //builder.appendLine("# ${mega.name}: no resource block")
                return false
            }

            val elementCategoryName = resources.findProperty("category", inline = true)?.value
            if (elementCategoryName == null) {
                //builder.appendLine("# ${mega.name}: no category given")
                return false
            }
            val category = ParadoxDefinitionSearch.search(elementCategoryName, "economic_category", selector(element.project, element.project.projectFile).definition().distinctByName()).find()
            if (category == null) {
                //builder.appendLine("# ${mega.name}: category has no value")
                return false
            }

            if (cachedEcoCategory != categoryToCheck) {
                cachedEcoCategory = categoryToCheck
                ecoCategoryCheckCache = HashMap()
            }

            val matches = checkEcoCategoryWithLineage(category, categoryToCheck, ecoCategoryCheckCache!!)

            return matches
        }
        fun hasEcoCategoryByName(element : ParadoxScriptDefinitionElement, categoryToCheck: String) : Boolean {
            val wantedCategory = ParadoxDefinitionSearch.search(categoryToCheck,"economic_category", selector(element.project, element.project.projectFile).definition().distinctByName()).find()
            if (wantedCategory == null) {
                //show("Failed to find economic category: $categoryName")
                return false
            }
            return hasEcoCategory(element, wantedCategory)
        }

        // checks if a given economic category is the same as, or a descendant of, another
        fun checkEcoCategoryWithLineage(categoryToCheck: ParadoxScriptDefinitionElement, categoryToMatch: ParadoxScriptDefinitionElement, map: MutableMap<ParadoxScriptDefinitionElement, Boolean>) : Boolean {
            if (map.containsKey(categoryToCheck)) {
                return map[categoryToCheck]!!
            }

            if (categoryToCheck == categoryToMatch) {
                map[categoryToCheck] = true
                return true
            }

            val parent = categoryToCheck.findProperty("parent")
            if (parent == null || parent.value == null) {
                map[categoryToCheck] = false
                return false
            }

            val selector = selector(categoryToCheck.project, categoryToCheck.context).definition().distinctByName()
            val parentCategory = ParadoxDefinitionSearch.search(parent.value!!,"economic_category", selector).find()

            if (parentCategory != null) { return checkEcoCategoryWithLineage(parentCategory, categoryToMatch, map) }

            return false
        }
    }
}



object GigaPsiUtils {

    fun nextNonWhiteSpaceSibling(element: PsiElement): PsiElement? {
        var nextElement: PsiElement? = element.nextSibling ?: element.parent.nextSibling

        while (nextElement != null) {
            if (nextElement is ParadoxScriptRootBlock) {
                nextElement = nextElement.firstChild
            } else if (nextElement !is PsiWhiteSpace) {
                return nextElement
            } else {
                nextElement = nextElement.nextSibling
            }
        }
        return null
    }

    fun prevNonWhiteSpaceSibling(element: PsiElement): PsiElement? {
        var prevElement: PsiElement? = element.prevSibling ?: element.parent.prevSibling

        while (prevElement != null) {
            if (prevElement !is PsiWhiteSpace) {
                return prevElement
            } else {
                prevElement = prevElement.prevSibling
            }
        }
        return null
    }
}

// #####################################################################################################################
// #### TAG DATA
// #####################################################################################################################

class DefinitionTag(val name: String, val shortDesc: String, val fullDesc: String) {

    fun entry(): Pair<String, DefinitionTag> {
        return Pair(name, this)
    }

    companion object {
        const val PREFIX = "## Tags:"
        val pattern by lazy { Regex("(?<=\\s)\\@([^\\s]+)") }

        val tags = mapOf(
            "megastructure" to mapOf(
                DefinitionTag("technical", "Technical Mega", "This megastructure isn't really a mega, it just uses the system for it. e.g. frameworld asteroid harvest, wrecked ship scrapping").entry(),
                DefinitionTag("ruined", "Ruined Megastructure", "This is a ruined megastructure and should be included in the trigger for checking whether a mega is ruined or not.").entry(),
                DefinitionTag("restored", "Restored Megastructure", "This is a repaired megastructure and should be included in the trigger for checking whether a mega has been restored.").entry(),
                DefinitionTag("megaproject", "Non-megastructure Project", "This mega is a construction project which doesn't result in an actual megastructure, so shouldn't count against supertensiles.").entry(),
                DefinitionTag("force_kilo", "Kilostructure Override", "This mega should be classed as a kilostructure for trigger purposes even if it doesn't have the right economic category.").entry(),
                DefinitionTag("force_giga", "Gigastructure Override", "This mega should be classed as a gigastructure for trigger purposes even if it doesn't have the right economic category.").entry(),
                DefinitionTag("force_final", "Final Stage Override", "This mega should count as the final mega in its series even if other non-technical megas upgrade from it.").entry(),
            ),
            "scripted_trigger" to mapOf(
                DefinitionTag("test", "Some desc", "Full desc").entry()
            )
        )

        fun getTags(definition: ParadoxScriptDefinitionElement) : Set<DefinitionTag>? {
            // get the previous comment
            val prevElement = GigaPsiUtils.prevNonWhiteSpaceSibling(definition)
            if (prevElement !is PsiComment) { return null }

            // check that it starts with the prefix
            val text = prevElement.text
            if (!text.startsWith(PREFIX)) { return null }

            // find valid tags
            val elementType = definition.definitionInfo?.typeConfig?.name ?: "unknown"
            val validTags = tags[elementType] ?: return null

            // array for found tags
            val tags : MutableSet<DefinitionTag> = mutableSetOf()

            // check each match against the tags
            val propertyMatches = pattern.findAll(text, PREFIX.length)
            for(match in propertyMatches) {
                // won't be null, or it wouldn't match the pattern
                val tag = match.groups[1]!!.value

                // insert valid tags
                if (validTags.containsKey(tag)) {
                    tags.add(validTags[tag]!!)
                }
            }
            return tags
        }
        fun getTagNames(definition: ParadoxScriptDefinitionElement) : Set<String>? { return getTags(definition)?.map { tag -> tag.name }?.toSet() }
    }
}

// #####################################################################################################################
// #### PLUGIN FUNCTION
// #####################################################################################################################

// rewrite the body of a specified scripted trigger with a list of megas which have the matching economic category or a child thereof
fun buildMegaCategoryList(triggerName: String, desc : String? = null, predicate: (ParadoxScriptDefinitionElement) -> Boolean) {
    if (project == null) { return }
    val thisProject = project!!

    // find the trigger that we're going to rewrite
    val trigger = ParadoxDefinitionSearch.search(triggerName,"scripted_trigger", selector(thisProject, thisProject.projectFile).definition().distinctByName()).find()
    if (trigger == null) {
        show("Failed to find scripted trigger: $triggerName")
        return
    }

    // start the block's text with a warning and description
    val builder = StringBuilder().append("{").appendLine("\t# $textGeneratedBlock")
    if (desc != null) {
        builder.appendLine("\t# $desc")
            .appendLine()
    }
    builder.appendLine("\t[[CONDITION]]").appendLine("\tor = {")

    // get a list of matching megas
    val megas: Iterable<ParadoxScriptDefinitionElement> = ParadoxDefinitionSearch.search("megastructure", selector(thisProject, thisProject.projectFile).definition().distinctByName()).findAll().sortedBy { mega -> mega.name }
    for (mega in megas) {
        if (!predicate(mega)) { continue }

        val locName = getElementName(mega)

        builder.append("\t\t\$CONDITION\$ = ${mega.name}")
        if (locName != mega.name) {
            builder.append(" # $locName")
        }
        builder.appendLine()
    }

    // create a new block with info and content
    builder.appendLine("\t}").appendLine("}")
    val newBlock = ParadoxScriptElementFactory.createBlock(thisProject, builder.toString())

    // finally, swap the trigger's block for the new one
    trigger.block?.replace(newBlock)
}

// #####################################################################################################################
// #### PLUGIN SETUP
// #####################################################################################################################

val pluginActionGroupId = "gigas.group"
val pluginActionGroup = DefaultActionGroup("Gigas", true)
pluginActionGroup.addTextOverride("MainMenu", "Gigastructures")
registerAction(pluginActionGroupId, "", ActionGroupIds.Menu.Tools, pluginActionGroup)

// regenerate lists for what counts as a kilo or giga
val gigaRegenMegaCategoryListsName = "Rebuild Kilo/Giga Category Triggers"
class GigaRegenMegaCategoryLists : AnAction() {
    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return

        WriteCommandAction.writeCommandAction(project).withName(gigaRegenMegaCategoryListsName).run<Throwable> {
            // test triggers for now
            buildMegaCategoryList("plugin_test_kilos_trigger", "Megas considered to be kilostructures, for supertensiles calculations etc") { def ->
                GigaListConditions.hasEcoCategoryByName(def, "giga_kilostructures")
                        || GigaListConditions.hasDefinitionTags(def, "force_kilo")
            }
            buildMegaCategoryList("plugin_test_gigas_trigger", "Megas considered to be gigastructures, for supertensiles calculations etc") { def ->
                GigaListConditions.hasEcoCategoryByName(def, "giga_gigastructures")
                        || GigaListConditions.hasDefinitionTags(def, "force_giga")
            }

            buildMegaCategoryList("plugin_test_ruined_trigger", "Ruined megastructures") { def -> GigaListConditions.hasDefinitionTags(def,"ruined") }
            buildMegaCategoryList("plugin_test_restored_trigger", "Repaired megastructures") { def -> GigaListConditions.hasDefinitionTags(def,"restored") }
            buildMegaCategoryList("plugin_test_technical_trigger", "Megas which are only megas by technicality - things which use the system but aren't strictly megastructures.") { def -> GigaListConditions.hasDefinitionTags(def,"technical") }
            buildMegaCategoryList("plugin_test_megaproject_trigger", "Megas which should be considered non-mega projects for supertensiles calculations etc") { def -> GigaListConditions.hasDefinitionTags(def,"megaproject") }
        }

        show("Trigger Rebuild Complete")
    }
}
val gigaRegenMegaCategoryLists = GigaRegenMegaCategoryLists()
gigaRegenMegaCategoryLists.addTextOverride("MainMenu", gigaRegenMegaCategoryListsName)
registerAction("gigas.regenlists", "",pluginActionGroupId, gigaRegenMegaCategoryLists)

class DefinitionPropertyAnnotator : Annotator {
    override fun annotate(element: PsiElement, holder: AnnotationHolder) {
        //println(element.text)
        // only comments
        if (element !is PsiComment) { return }
        // only top level elements
        if (element.parent !is ParadoxScriptRootBlock && element.parent !is ParadoxScriptFile) { return }

        val text = element.text
        // only specially annotated lines
        if (!text.startsWith(DefinitionTag.PREFIX)) { return }
        println("STARTED")

        // get next non-whitespace element or bail
        val nextElement: PsiElement = GigaPsiUtils.nextNonWhiteSpaceSibling(element) ?: return
        // only definition lines
        if (nextElement !is ParadoxScriptDefinitionElement) { return }
        // work out what type of thing we're looking at for getting valid tags
        val elementType = nextElement.definitionInfo?.typeConfig?.name ?: "unknown"
        // get the valid tags or abort if there aren't any
        val validTags = DefinitionTag.tags[elementType] ?: return

        // mark the prefix
        val prefixRange = TextRange.from(element.textRange.startOffset, DefinitionTag.PREFIX.length)
        holder.newSilentAnnotation(HighlightSeverity.INFORMATION).range(prefixRange).textAttributes(GigaToolsAttributesKeys.PROPERTY_LINE_KEY).create()

        // find all properties via pattern
        val propertyMatches = DefinitionTag.pattern.findAll(text, DefinitionTag.PREFIX.length)
        for(match in propertyMatches) {
            // the @ at the start
            val markerRange = TextRange.from(element.textRange.startOffset + match.range.first, 1)
            holder.newSilentAnnotation(HighlightSeverity.INFORMATION).range(markerRange).textAttributes(GigaToolsAttributesKeys.PROPERTY_KEY).create()

            // won't be empty or null otherwise it wouldn't match the pattern
            val property = match.groups[1]!!
            val propertyRange = TextRange.from(element.textRange.startOffset + property.range.first, property.range.last - property.range.first + 1)
            val propertyName = property.value

            if (validTags.containsKey(propertyName)) {
                holder
                    .newAnnotation(HighlightSeverity.INFORMATION, validTags[propertyName]?.fullDesc ?: "")
                    .range(propertyRange)
                    .textAttributes(GigaToolsAttributesKeys.PROPERTY_NAME_KEY)
                    .create()
            } else {
                holder
                    .newAnnotation(HighlightSeverity.WARNING, "Unknown tag \"$propertyName\" for type $elementType")
                    .range(propertyRange)
                    .highlightType(ProblemHighlightType.LIKE_UNKNOWN_SYMBOL)
                    .create()
            }
        }

        //println("ANNOTATED: $text")
    }
}
val definitionPropertyAnnotator = DefinitionPropertyAnnotator()
LanguageAnnotators.INSTANCE.addExplicitExtension(ParadoxScriptLanguage, definitionPropertyAnnotator)

class DefinitionPropertyCompletionContributor : CompletionContributor() {
    init {
        extend(CompletionType.BASIC, PlatformPatterns.psiElement(PsiComment::class.java),
            object: CompletionProvider<CompletionParameters>() {
                override fun addCompletions(parameters: CompletionParameters, context: ProcessingContext, resultSet: CompletionResultSet) {
                    // get the comment element
                    val comment = parameters.position

                    // find the next element and check that it's a definition
                    val nextElement = GigaPsiUtils.nextNonWhiteSpaceSibling(comment)
                    if (nextElement !is ParadoxScriptDefinitionElement) { return }
                    // get the valid tags for the definition's type
                    val elementType = nextElement.definitionInfo?.typeConfig?.name ?: "unknown"
                    val validTags = DefinitionTag.tags[elementType] ?: return

                    // add all valid tags to the list, along with their descriptions
                    resultSet.addAllElements(validTags.keys.map { s -> LookupElementBuilder.create(s).withTypeText( validTags[s]?.shortDesc ) })
                }
            })
    }
}
// register the completion thingy
val contributor = DefinitionPropertyCompletionContributor()
val languageExtension = CompletionContributor::class.java.getStaticField<LanguageExtension<CompletionContributor>>("INSTANCE")
languageExtension.addExplicitExtension(ParadoxScriptLanguage, contributor, pluginDisposable)

// make sure stuff is unloaded
pluginDisposable.whenDisposed {
    LanguageAnnotators.INSTANCE.removeExplicitExtension(ParadoxScriptLanguage, definitionPropertyAnnotator)
}

println("registered")