package gigatools

import com.intellij.openapi.actionSystem.*
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.editor.DefaultLanguageHighlighterColors
import com.intellij.openapi.editor.colors.TextAttributesKey
import com.intellij.openapi.project.Project
import liveplugin.ActionGroupIds
import org.jetbrains.annotations.NotNull

import static liveplugin.PluginUtil.*

import icu.windea.pls.script.psi.ParadoxScriptDefinitionElement

// depends-on-plugin icu.windea.pls

abstract class PluginData {
    static String actionGroupId = "gigas.group"
    static String textGeneratedBlock = "WARNING: The contents of this block are generated by script, any manual changes will be overwritten"

    static def definitionTags = [
            "megastructure" : [
                    "ruined" : "Some desc for ruined"
            ]
    ]
}

abstract class GigaToolsAttributeKeys {
    static TextAttributesKey PROPERTY_LINE_KEY = TextAttributesKey.createTextAttributesKey("GIGA_TOOLS.PROPERTY_LINE", DefaultLanguageHighlighterColors.STRING)
    static TextAttributesKey PROPERTY_KEY = TextAttributesKey.createTextAttributesKey("GIGA_TOOLS.PROPERTY", DefaultLanguageHighlighterColors.FUNCTION_DECLARATION)
    static TextAttributesKey PROPERTY_NAME_KEY = TextAttributesKey.createTextAttributesKey("GIGA_TOOLS.PROPERTY_NAME", DefaultLanguageHighlighterColors.CLASS_NAME)
}

String getElementName(ParadoxScriptDefinitionElement element) {

}

class RegenMegaCategoryLists extends AnAction {
    static String name = "Rebuild Kilo/Giga Category Triggers"

    @Override
    void actionPerformed(@NotNull AnActionEvent event) {
        Project project = event.project
        if (project == null) { return }

        WriteCommandAction.writeCommandAction(project).withName(name).run {
            // test triggers for now
            //buildMegaCategoryList(project, "plugin_test_kilos_trigger", "giga_kilostructures")
            //buildMegaCategoryList(project, "plugin_test_gigas_trigger", "giga_gigastructures")
            show("hello!  dfdfd")
        }

        show("Trigger Rebuild Complete")
    }

    static void register() {
        RegenMegaCategoryLists action = new RegenMegaCategoryLists()
        action.addTextOverride("MainMenu", name)
        registerAction("gigas.regenlists", "", PluginData.actionGroupId, action)
    }
}


def pluginActionGroup = new DefaultActionGroup("Gigas", true)
pluginActionGroup.addTextOverride("MainMenu", "Gigastructures")
registerAction(PluginData.actionGroupId, "", ActionGroupIds.Menu.Tools, pluginActionGroup)

RegenMegaCategoryLists.register()