name: Bug
description: Help us find and fix bugs. Please use other issue reports if they are more specific about your issue.
title: Summary of Bug
labels: 'Bug'
body:
  - type: markdown
    attributes:
      value: "## Basic Information:"
  - type: input
    id: operating_system
    attributes:
      label: OS
      description: What operating system were you using?
    validations:
      required: true
  - type: input
    id: stellaris_version
    attributes:
      label: Stellaris Version
      description: |
        Write the **full version number** of Stellaris that you were playing on - you can find it in the bottom of the game's main menu, for example "Cetus v4.3.7 (4f3c)".
        **SPECIFY THE VERSION NUMBER - DO NOT SIMPLY WRITE IN "CURRENT", "LATEST", ETC.**
    validations:
      required: true
  - type: input
    id: gigas_version
    attributes:
      label: Gigastructures Version
      description: |
        Write the **full version number** of Gigastructures that you were playing on - for example, 3.36.2 or 3.37.0 H2.
        **SPECIFY THE VERSION NUMBER - DO NOT SIMPLY WRITE IN "CURRENT", "LATEST", ETC.**
    validations:
      required: true
  - type: input
    id: other_mods
    attributes:
      label: Other Mods
      description: Please list **any and all** other mods that you were using besides Gigastructures itself
    validations:
      required: true
  - type: dropdown
    id: steam
    attributes:
      label: Were you using Steam?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: multiplayer
    attributes:
      label: Were you in multiplayer?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
  - type: checkboxes
    id: dlcs
    attributes:
      label: Which DLCs do you NOT have? (Ignore this question if you have all listed ones)
      options:
        - label: Leviathans
        - label: Humanoids
        - label: Apocalypse
        - label: Distant Stars
        - label: MegaCorp
        - label: Lithoids
        - label: Ancient Relics
        - label: Federations
        - label: Necroids
        - label: Aquatics
        - label: Nemesis
        - label: Toxoids
        - label: Overlord
        - label: First Contact
        - label: Galactic Paragons
        - label: Astral Planes
        - label: The Machine Age
        - label: Cosmic Storms
        - label: Grand Archive
        - label: Biogenesis
        - label: Infernals
        - label: Shadows of the Shroud
  - type: markdown
    attributes:
      value: "## Issue Information:"
  - type: textarea
    id: description
    attributes:
      label: Description of the Issue
      description: Please describe the bug that you encountered.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: If possible, please explain step-by-step how to recreate this bug.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If you have any screenshots of the issue, post them in this box to help show the Gigastructures Team what the issue is.
  - type: markdown
    attributes:
      value: "## Important Files:"
  - type: textarea
    id: save_file
    attributes:
      label: Save File
      description: |
        Path locations may vary due to installation/hardware but for Windows users they can be found through your documents folder - **C\Users\USER\Documents\Paradox Interactive\Stellaris\save games**
        **NOTE*:* due to how Github handles files, saves will need to be uploaded as a zipped folder. This can be done by right-clicking and selecting the Send to > Compressed (zipped) folder option and it will create a new folder that can be uploaded to Github.
  - type: textarea
    id: log_files
    attributes:
      label: Log Files
      description: |
        Path locations may vary due to installation/hardware but for Windows users they can be found through your documents folder - **C\Users\USER\Documents\Paradox Interactive\Stellaris\logs** (the most important ones are **game.log**, **error.log** and **system.log**)
        **NOTE:** The log files are overwritten every time Stellaris is launched, so make sure to grab the log files before restarting the game.
  - type: checkboxes
    attributes:
      label: Important Files Attached
      options:
      - label: I have attached the game/error logs and/or a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information was included to determine the cause of this issue.
    validations:
      required: true
